# Generated by Django 4.2.6 on 2023-11-13 19:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_holder', models.CharField(default=core.models.Record.default_RecHold, max_length=100)),
                ('record_holders_age', models.IntegerField(blank=True)),
                ('record_holders_city', models.CharField(blank=True, max_length=100)),
                ('record_holders_region', models.CharField(choices=[('CK', 'Черкаська Обл'), ('CG', 'Чернігівська Обл'), ('CT', 'Чернівецька Обл'), ('CR', 'АР Крим'), ('DN', 'Донецька Обл'), ('DP', 'Дніпропетровська Обл'), ('IF', 'Івано-Франківська Обл'), ('KR', 'Харківська Обл'), ('KS', 'Херсонська Обл'), ('KN', 'Хмельницька Обл'), ('KD', 'Кіровоградська Обл'), ('KY', 'Київська Обл'), ('LV', 'Львівська Обл'), ('OD', 'Одеська Обл'), ('PT', 'Полтавська Обл'), ('SU', 'Сумська Обл'), ('TP', 'Тернопільська Обл'), ('VN', 'Вінницька Обл'), ('VL', 'Волинська Обл'), ('ZK', 'Закарпатська Обл'), ('ZP', 'Запоріжська Обл'), ('ZT', 'Житомирська Обл'), ('MK', 'Миколаївська Обл'), ('RV', 'Рівненська Обл'), ('LH', 'Луганська Обл')], default='KY', max_length=2)),
                ('record_holder_image', models.ImageField(upload_to='./upload/')),
                ('coordinate_y', models.FloatField(default=0.0)),
                ('coordinate_x', models.FloatField(default=0.0)),
            ],
        ),
    ]
