# Generated by Django 4.2.6 on 2023-11-15 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='../upload/')),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='record_holder_image',
            field=models.ImageField(upload_to='../upload/'),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_holders_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.regions'),
        ),
    ]
