# Generated by Django 4.2.6 on 2023-11-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_regions_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regions',
            name='image',
            field=models.ImageField(upload_to='../upload/'),
        ),
    ]
