# Generated by Django 4.2.6 on 2023-11-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_regions_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_holder_image',
            field=models.ImageField(upload_to='upload/recordHolders'),
        ),
        migrations.AlterField(
            model_name='regions',
            name='image',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
