# Generated by Django 4.2.7 on 2023-11-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_record_record_holders_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_holder_image',
            field=models.ImageField(default='default.png', upload_to='upload/recordHolders'),
        ),
    ]
