# Generated by Django 4.2.7 on 2023-11-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_record_record_holder_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_holder_image',
            field=models.ImageField(default='upload/recordHolders/default.png', upload_to='upload/recordHolders'),
        ),
    ]
